# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-21 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', 'sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='default', max_length=100, verbose_name='ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email1',
            field=models.CharField(default='default', max_length=100, verbose_name='correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='email2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='correo electrónico (Alternativo)'),
        ),
        migrations.AddField(
            model_name='company',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula Ciudadanía')], default='default', max_length=10, verbose_name='tipo documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default='default', max_length=500, verbose_name='dirección de domicilio principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre o Razón Social'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=50, verbose_name='no documento'),
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(default=0, max_length=20, verbose_name='teléfono'),
            preserve_default=False,
        ),
    ]
