# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import inventario.models


class Migration(migrations.Migration):

    initial = True

    #dependencies = [
    #    ('inventario', 'sequence'),
    #]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='nombre')),
                ('nit', models.CharField(max_length=50, verbose_name='nit')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='dirección')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='celular')),
                ('legal_representative', models.CharField(blank=True, max_length=500, null=True, verbose_name='representante legal')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='company/img', verbose_name='imagen')),
                ('photo_thumbnail1', models.ImageField(blank=True, null=True, upload_to='company/img', verbose_name='imagen 250x250')),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='HardwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=200, null=True, verbose_name='marca')),
                ('model', models.CharField(blank=True, max_length=200, null=True, verbose_name='modelo')),
                ('serie', models.CharField(blank=True, max_length=200, null=True, verbose_name='serie')),
                ('size', models.CharField(blank=True, max_length=200, null=True, verbose_name='tamaño')),
                ('features', models.CharField(blank=True, max_length=500, null=True, verbose_name='características')),
            ],
            options={
                'verbose_name': 'Componente de Hardware',
                'verbose_name_plural': 'Componentes de Hardware',
            },
        ),
        migrations.CreateModel(
            name='HardwareComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Componente Hardware',
                'verbose_name_plural': 'Tipos de Componente Hardware',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', inventario.models.MACAddressField(blank=True, max_length=17, null=True, verbose_name='mac address')),
                ('shared', models.CharField(blank=True, max_length=200, null=True, verbose_name='compartido')),
                ('printers', models.CharField(blank=True, max_length=200, null=True, verbose_name='impresoras')),
                ('os', models.CharField(blank=True, max_length=200, null=True, verbose_name='sistema operativo')),
                ('machine_sequence', models.CharField(blank=True, max_length=200, null=True, verbose_name='número de secuencia')),
                ('buyed_date', models.DateField(blank=True, null=True, verbose_name='fecha de compra')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='proveedor')),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meses garantía')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='inventario.Company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Máquina',
            },
        ),
        migrations.CreateModel(
            name='SoftwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('release', models.CharField(blank=True, max_length=200, null=True, verbose_name='version')),
                ('compilation', models.CharField(blank=True, max_length=200, null=True, verbose_name='compilación')),
                ('bits', models.CharField(blank=True, max_length=200, null=True, verbose_name='bits')),
                ('features', models.CharField(blank=True, max_length=500, null=True, verbose_name='características')),
            ],
            options={
                'verbose_name': 'Componente de Software',
                'verbose_name_plural': 'Componentes de Software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Componente Software',
                'verbose_name_plural': 'Tipos de Componente Software',
            },
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_tipo_componente', to='inventario.SoftwareComponentType', verbose_name='tipo_componente'),
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_machine', to='inventario.Machine', verbose_name='máquina'),
        ),
        migrations.AddField(
            model_name='hardwarecomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_tipo_componente', to='inventario.HardwareComponentType', verbose_name='tipo_componente'),
        ),
        migrations.AddField(
            model_name='hardwarecomponent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_machine', to='inventario.Machine', verbose_name='máquina'),
        ),
    ]
