# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', 'sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo_thumbnail1',
            field=models.ImageField(blank=True, null=True, upload_to='company/img', verbose_name='imagen 150x150'),
        ),
    ]
