# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('person_contact', models.CharField(max_length=500)),
                ('nit', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=200)),
                ('shared', models.CharField(max_length=200)),
                ('printers', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Company')),
            ],
        ),
    ]
