# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True


    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='nombre')),
                ('nit', models.CharField(max_length=50, verbose_name='nit')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='dirección')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono')),
                ('cellphone', models.CharField(blank=True, max_length=15, null=True, verbose_name='celular')),
                ('legal_representative', models.CharField(blank=True, max_length=500, null=True, verbose_name='representante legal')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='company/img', verbose_name='imagen')),
            ],
            options={
                'verbose_name': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('ip', models.CharField(max_length=200)),
                ('mac_address', models.CharField(max_length=200, verbose_name='mac address')),
                ('shared', models.CharField(max_length=200, verbose_name='compartido')),
                ('printers', models.CharField(max_length=200, verbose_name='impresoras')),
                ('os', models.CharField(max_length=200, verbose_name='sistema operativo')),
                ('machine_sequence', models.CharField(max_length=200, null=True, verbose_name='número de secuencia')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='inventario.Company', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'Máquina',
            },
        ),
    ]
