# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 02:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_auto_20180121_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.')], verbose_name='digito verificación'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_legal_representative',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='correo electrónico representante legal'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Only alphanumeric characters are allowed.')], verbose_name='no documento'),
        ),
    ]
