# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_auto_20171106_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de compra'),
            preserve_default=False,
        ),
    ]
