# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa'},
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name': 'Máquina'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=500, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=500, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=500, verbose_name='nit'),
        ),
        migrations.AlterField(
            model_name='company',
            name='person_contact',
            field=models.CharField(max_length=500, verbose_name='persona de contacto'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Company', verbose_name='empresa'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac_address',
            field=models.CharField(max_length=200, verbose_name='mac address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os',
            field=models.CharField(max_length=200, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='printers',
            field=models.CharField(max_length=200, verbose_name='impresoras'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shared',
            field=models.CharField(max_length=200, verbose_name='compartido'),
        ),
    ]
