# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20171106_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='warranty_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='meses garantía'),
        ),
    ]
