# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-10 03:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180207_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='hardwarecomponent',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='hardwarecomponenttype',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='softwarecomponenttype',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='dv',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo acepta caractéres numéricos.')], verbose_name='dv'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nit',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'Solo acepta caractéres numéricos.')], verbose_name='no documento'),
        ),
    ]
