# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20171004_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='company/img', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='company',
            name='person_contact',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='persona de contacto'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='inventario.Company', verbose_name='empresa'),
        ),
    ]
