# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20171106_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='meses garantía'),
        ),
    ]
