# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20171025_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='brand',
            field=models.CharField(max_length=200, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='features',
            field=models.CharField(max_length=500, null=True, verbose_name='características'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='model',
            field=models.CharField(max_length=200, null=True, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='serie',
            field=models.CharField(max_length=200, null=True, verbose_name='serie'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='size',
            field=models.CharField(max_length=200, null=True, verbose_name='tamaño'),
        ),
    ]
