# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20171025_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='nombre')),
                ('release', models.CharField(blank=True, max_length=200, null=True, verbose_name='version')),
                ('compilation', models.CharField(blank=True, max_length=200, null=True, verbose_name='compilación')),
                ('bits', models.CharField(blank=True, max_length=200, null=True, verbose_name='bits')),
                ('features', models.CharField(blank=True, max_length=500, null=True, verbose_name='características')),
            ],
            options={
                'verbose_name': 'Componente de Software',
            },
        ),
        migrations.CreateModel(
            name='SoftwareComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Component Software',
            },
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_tipo_componente', to='inventario.HardwareComponentType', verbose_name='tipo_componente'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='features',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='características'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hw_machine', to='inventario.Machine', verbose_name='máquina'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='serie',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='serie'),
        ),
        migrations.AlterField(
            model_name='hardwarecomponent',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='tamaño'),
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_tipo_componente', to='inventario.SoftwareComponentType', verbose_name='tipo_componente'),
        ),
        migrations.AddField(
            model_name='softwarecomponent',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sw_machine', to='inventario.Machine', verbose_name='máquina'),
        ),
    ]
