# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20171026_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardwarecomponenttype',
            options={'verbose_name': 'Tipo de Componente Hardware', 'verbose_name_plural': 'Tipos de Componente Hardware'},
        ),
        migrations.AlterModelOptions(
            name='softwarecomponenttype',
            options={'verbose_name': 'Tipo de Componente Software', 'verbose_name_plural': 'Tipos de Componente Software'},
        ),
        migrations.AlterField(
            model_name='machine',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='mac_address',
            field=inventario.models.MACAddressField(blank=True, max_length=17, null=True, verbose_name='mac address'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_sequence',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='número de secuencia'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='printers',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='impresoras'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shared',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='compartido'),
        ),
    ]
