# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_empresa', to='inventario.Company', verbose_name='empresa'),
        ),
    ]
