# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20171029_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('TECNICO', 'Técnico'), ('CLIENTE_ADMIN', 'Cliente Administrador'), ('CLIENTE', 'Cliente')], max_length=100, null=True),
        ),
    ]
