# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='year_in_school',
            new_name='tipo_usuario',
        ),
    ]
