# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0001_auto_20171126_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.CharField(max_length=100, verbose_name='resumen')),
                ('description', models.TextField(max_length=1500, verbose_name='descripción')),
                ('remote_diagnosis', models.TextField(blank=True, max_length=1500, null=True, verbose_name='diagnóstico remoto')),
                ('phone_diagnosis', models.TextField(blank=True, max_length=1500, null=True, verbose_name='diagnóstico teléfono')),
                ('visit_diagnosis', models.TextField(blank=True, max_length=1500, null=True, verbose_name='diagnóstico visita')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('severity', models.CharField(choices=[('5', 'Grave'), ('4', 'Importante'), ('3', 'Medio'), ('2', 'Simple'), ('1', 'Mínimo'), ('0', 'Sin Clasificar')], default='0', max_length=1, verbose_name='gravedad')),
                ('status', models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='inventario.Machine', verbose_name='maquina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Incidente',
            },
        ),
    ]
