# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20171106_2056'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='inventario.Machine', verbose_name='maquina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(blank=True, choices=[('O', 'Abierto'), ('C', 'Cerrado')], default='O', max_length=1, null=True, verbose_name='estado'),
        ),
    ]
